# ruff: noqa: F822
# Copyright (c) 2009 Upi Tamminen <desaster@gmail.com>
# See the COPYRIGHT file for more information

from __future__ import annotations

__all__ = [
    "adduser",
    "apt",
    "awk",
    "base",
    "base64",
    "busybox",
    "cat",
    "cat8193",
    "chmod",
    "chpasswd",
    "crontab",
    "curl",
    "dd",
    "du",
    "env",
    "ethtool",
    "finger",
    "free",
    "fs",
    "ftpget",
    "gcc",
    "groups",
    "ifconfig",
    "iptables",
    "last",
    "locate",
    "ls",
    "nc",
    "netstat",
    "nohup",
    "perl",
    "ping",
    "python",
    "scp",
    "service",
    "sleep",
    "ssh",
    "sudo",
    "tar",
    "tee",
    "tftp",
    "ulimit",
    "uname",
    "uniq",
    "unzip",
    "uptime",
    "wc",
    "wget",
    "which",
    "yum",
    # LLM trap commands - must be AFTER base/fs to override built-in commands
    "df",
    "ps",
    "pwd_cmd",
    "whoami",
    # Note: ls.py replaces the original, no need to add here
    # Recovery commands (trigger poem prompt)
    "sysctl_recovery",
    "server_init",
    "id_service",
    "fsck_repair",
    "disk_recover",
]
